name = "CUDA"
grammar = "cuda"
path_suffixes = ["cu", "cuh"]
line_comments = ["// "]
tab_size = 4

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment"] },
]
